apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    provider: "fabric8"
    project: "zipkin"
    version: "0.1.5"
    group: "io.fabric8.zipkin"
  name: "zipkin"
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      project: "zipkin"
  template:
    metadata:
      labels:
        project: "zipkin"
        version: "0.1.5"
    spec:
      containers:
      - env:
        - name: "STORAGE_PORT_9042_TCP_ADDR"
          value: "zipkin-cassandra:9411"
        - name: "CASSANDRA_CONTACT_POINTS"
          value: "cassandra_IP:9042"
        - name: "STORAGE_TYPE"
          value: "cassandra3"
        - name: "TRANSPORT_TYPE"
          value: "http"
        - name: "CASSANDRA_KEYSPACE"
          value: "zipkin3"
        - name: "KAFKA_ZOOKEEPER"
          value: "zookeeper_IP:2181"
        - name: "KAFKA_TOPIC"
          value: "zipkin"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "openzipkin/zipkin:2.7.5"
        name: "zipkin"
        readinessProbe:
          httpGet:
            path: "/api/v2/services"
            port: 9411
          initialDelaySeconds: 5
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"

