apiVersion: v1
kind: PersistentVolume
metadata:
  name: test1
  namespace: develop
spec:
  capacity:
    storage: 1G
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfs-share/test
    server: 10.0.0.154

