---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace: develop
spec:
  clusterIP: 10.106.39.210
  ports:
    - port: 9042
  selector:
    app: cassandra

